spring.application.name=timetracker-backend
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=timetrackerapp
Timetracker.origin=${TimeTracker_ORIGIN}
spring.data.mongodb.auto-index-creation=true
server.port=3030